### ISSUE TITLE
Handle existing folder or tests will fail

### ISSUE THREAD

**Issue by weskamm** [ocavue/jest-puppeteer-istanbul#1]
Tests will fail when the coverage directory already exists.
Can be easily avoided by adding a check or try / catch around line 23 in storage.js

https://github.com/ocavue/jest-puppeteer-istanbul/blob/acf1e6e3beaaf99bbd3264fcdeed30ba1c928e40/src/storage.ts#L26

**Comment by ocavue** [comment]
That's strange. I added `recursive: true`, which should not raise an error if the folder exists.

I will look into this.

**Comment by ocavue** [comment]
@weskamm Can you paste your error stack here.

**Comment by weskamm** [comment]
```
EEXIST: file already exists, mkdir '/test/coverage'

      at CoverageStorage.write (node_modules/jest-puppeteer-istanbul/lib/storage.js:22:14)
      at Object.<anonymous> (node_modules/jest-puppeteer-istanbul/lib/setup.js:24:25)
      at fulfilled (node_modules/jest-puppeteer-istanbul/lib/setup.js:4:58)
```

**Comment by ocavue** [comment]
I think `/test/coverage` is a exists **file**, instead of a **folder**.

**Comment by weskamm** [comment]
No, its the default coverage folder that i even havent configured (containing coverage-puppeteer-istanbul.json etc)
Wrapping that line in try catch makes it work.

**Comment by ocavue** [comment]
node v8 doesn't have `recursive: true`. I didn't know that before.

![image](https://user-images.githubusercontent.com/24715727/65408723-99a7c080-de18-11e9-8507-f175d93b24ca.png)

I will release a version to fix it.

**Comment by weskamm** [comment]
nice, thanks!

**Comment by ocavue** [comment]
@weskamm Upgrade `jest-puppeteer-istanbul` v0.2.1 should fix this issue.

**Comment by ocavue** [comment]
Feel free to reopen it if this problem still persists.

**Comment by weskamm** [comment]
Seems to be working fine, thanks again!

**Comment by ocavue** [comment]
You are welcome. Happy to help others with this project.
