### ISSUE TITLE
Usage without babel

### ISSUE THREAD

**Issue by nmfzone** [ocavue/jest-puppeteer-istanbul#48]
Hey, sorry for bothering you via this issue.

I just want to know, is it possible to use this package in Angular? since AFAIK angular doesn't use babel. Thanks

**Comment by ocavue** [comment]
This package is based on the [`babel-plugin-istanbul`](https://github.com/istanbuljs/babel-plugin-istanbul) so currently, it's not possible to use this package without babel.

I haven't used Angular before. Based on what I learn from google, Angular use TypeScript(tsc) and Webpack to build the application. Maybe you can try https://www.npmjs.com/package/coverage-istanbul-loader, which doesn't need babel under the hood.

**Comment by nmfzone** [comment]
Ah, thanks for the clarification, since I've spent some hours just to figured out what is happened under the hood. Thanks for pointing me to that package, but it seems I've found the official package that maybe can be used in Angular (https://github.com/istanbuljs/puppeteer-to-istanbul).
