### ISSUE TITLE
Is there way to ignore some file?

### ISSUE THREAD

**Issue by lastnigtic** [ocavue/jest-puppeteer-istanbul#5]
I'm using "coveragePathIgnorePatterns" and "collectCoverageFrom", but it seems not working?

Looking from help ^_^

**Comment by lastnigtic** [comment]
I found it can not get "coveragePathIgnorePatterns" config from globalconfig

**Comment by ocavue** [comment]
I will check this later this weekend.

**Comment by ocavue** [comment]
@lastnigtic Please try version `0.4.2`, which should repeat `coveragePathIgnorePatterns` as well as `collectCoverageFrom` in your Jest configuration.

Feel free to comment if this version doesn't solve your issue.

**Comment by lastnigtic** [comment]
I found nothing in floder 'lib' after update.
Did you published an empty package?
I solve this problem by fork and write my reporter.

**Comment by ocavue** [comment]
> Did you published an empty package?

My mistake. I should publish a release with CI/CD instead of my PC. Version `0.4.3` fix it.

**Comment by ocavue** [comment]
Closing since it's fixed.

Feel free to reopen if it still doesn't work.
